#!/bin/bash

# Script to generate a threat using live OpenAI API
# This demonstrates the difference between mock and real AI-generated threat analysis

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
echo "=========================================="
echo "  OpenAI Live Threat Generation Demo"
echo "=========================================="
echo -e "${NC}"

# Check if OpenAI API key is set
if [ -z "$OPENAI_API_KEY" ]; then
    echo -e "${YELLOW}⚠️  OPENAI_API_KEY environment variable is not set${NC}\n"
    echo -e "Please enter your OpenAI API key:"
    echo -e "${BLUE}(You can get one from: https://platform.openai.com/api-keys)${NC}"
    read -s OPENAI_API_KEY
    echo ""
    
    if [ -z "$OPENAI_API_KEY" ]; then
        echo -e "${RED}❌ No API key provided. Exiting.${NC}"
        exit 1
    fi
fi

echo -e "${GREEN}✅ OpenAI API key detected${NC}\n"

# Show cost warning
echo -e "${YELLOW}⚠️  COST WARNING:${NC}"
echo -e "This will make a real API call to OpenAI (gpt-4o-mini model)"
echo -e "Estimated cost: ~$0.001 per threat generation"
echo -e ""
read -p "Do you want to proceed? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo -e "${YELLOW}Demo cancelled.${NC}"
    exit 0
fi

echo -e "\n${BLUE}[1/4] Creating Kubernetes secret with OpenAI API key...${NC}"
kubectl create secret generic openai-api-key \
    --from-literal=OPENAI_API_KEY="$OPENAI_API_KEY" \
    -n soc-agent-demo \
    --dry-run=client -o yaml | kubectl apply -f -

echo -e "${GREEN}✅ Secret created${NC}\n"

echo -e "${BLUE}[2/4] Updating backend deployment to use live OpenAI API...${NC}"

# First, set the FORCE_MOCK_MODE to 0 to disable mock mode
kubectl set env deployment/soc-agent-backend -n soc-agent-demo FORCE_MOCK_MODE=0

# Then, add the OpenAI API key from the secret
kubectl set env deployment/soc-agent-backend -n soc-agent-demo \
    --from=secret/openai-api-key

echo -e "${GREEN}✅ Deployment updated${NC}\n"

echo -e "${BLUE}[3/4] Waiting for backend pods to restart...${NC}"
kubectl rollout status deployment/soc-agent-backend -n soc-agent-demo --timeout=120s

echo -e "${GREEN}✅ Backend pods restarted${NC}\n"

# Give pods a moment to fully initialize
echo -e "${YELLOW}Waiting 5 seconds for pods to initialize...${NC}"
sleep 5

echo -e "${BLUE}[4/4] Generating threat with live OpenAI API...${NC}\n"

# Trigger a threat using the API
# The backend will generate a realistic threat scenario and analyze it with OpenAI
# Valid threat types: bot_traffic, proxy_network, device_compromise, anomaly_detection, rate_limit_breach, geo_anomaly
TRIGGER_DATA='{"threat_type": "bot_traffic"}'

echo -e "${CYAN}Triggering threat generation:${NC}"
echo "$TRIGGER_DATA" | jq .

echo -e "\n${CYAN}Calling OpenAI API (this may take 5-10 seconds)...${NC}\n"

# Make API call and capture response
RESPONSE=$(curl -s -X POST http://localhost:8080/api/threats/trigger \
    -H "Content-Type: application/json" \
    -d "$TRIGGER_DATA")

echo -e "${GREEN}✅ Threat generated successfully!${NC}\n"

echo -e "${CYAN}=========================================="
echo "  OpenAI-Generated Threat Analysis"
echo "==========================================${NC}\n"

# Extract and display key fields
THREAT_ID=$(echo "$RESPONSE" | jq -r '.id // "N/A"')
SEVERITY=$(echo "$RESPONSE" | jq -r '.severity // "N/A"')
THREAT_TYPE=$(echo "$RESPONSE" | jq -r '.threat_type // "N/A"')
ANALYSIS=$(echo "$RESPONSE" | jq -r '.analysis // "N/A"')

echo -e "${BLUE}Threat ID:${NC} $THREAT_ID"
echo -e "${BLUE}Severity:${NC} $SEVERITY"
echo -e "${BLUE}Threat Type:${NC} $THREAT_TYPE"
echo ""
echo -e "${BLUE}AI Analysis:${NC}"
echo "$ANALYSIS" | fold -w 80 -s

echo -e "\n${CYAN}Full Response (JSON):${NC}"
echo "$RESPONSE" | jq .

echo -e "\n${GREEN}=========================================="
echo "  Demo Complete!"
echo "==========================================${NC}\n"

echo -e "${YELLOW}💡 Key Observations:${NC}"
echo -e "   • The analysis above was generated by OpenAI's GPT-4o-mini model"
echo -e "   • Compare this with mock mode to see the difference in quality"
echo -e "   • Cost: ~\$0.001 per threat generation"
echo ""
echo -e "${YELLOW}💡 To revert back to mock mode, run:${NC}"
echo -e "   ${BLUE}./revert_to_mock_mode.sh${NC}\n"

