---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-api-key
  namespace: soc-agent-demo
spec:
  encryptedData:
    openai-api-key: AgB5isE07HBknpG4L4FnvekM+HXbdxCVYAoGFXV3w1x+XxvKmSsSfntgelVvFz4SU65XNdmzm0vQpBuHuFQlhvaU4sqjtt3HM1u9mvfjfPUz7qb0LCWqGzX1SOljK304qev+SbOA8URP8yL2CcUL5X/1sgneCFmkGRaCY9+UUestYIr5jqF9Dvr0blT8nssCdr+RHwv23ir3p7TahmJCfAb3LXvnXXGGn+RpN6SfNumS5805ylIS8oU4uVXy4gEOvbEE4UNYxhQppGBwSPccg/NPnywLoMs2Vurw1Cq/6JEyq+H9/bgdgDqeZDk3S7EydU3jyhIcwr9EHFu+pzIZpCWmTWCMUmDSOnjqcYCnPsT8qnPi48hiVIjcsdctn/+hF4xaK8l/0pj0AIxq9PbBv4I3FaQV9nU1gKtfnrH1rbFSPOnIJ3stwlrdXExseEJYSWJ4LKCb4ZZPGmNk2T144VJ7DfPlI7Lw6aG20j7Yco/3i9e0pc0OGkWOtBrCU+mkxpJCMlCZ+/zIQ7G3VaeL3hLIAK7ib6NcM6To0X3t3qoqxFS9PQ/uB9DRQAEg1b3Rtcrf2CdDcv1Emjtdeh4x0jf+2d59R681CYSWxyiZDwLcE3LN304pWnK0lLvooKD7pu/bhrcPpu7Fc3kgHHyInsvVJkITCIw2sS2g+jvoBYuy7u+ZB5GADGr/PeDr5ZTR6R26JjJhh3Y1qSxjjIQfUYRRDu2NslPazii7lAhIJS2TP/tZBIbWujU2S93HhA==
    virustotal-api-key: AgAEQQQ3nrj3q+/p9IpjXmtY96sCJAAYaXvba9PUKf/I433W23DK9oPkUL0P+v8ybWW1ip6tnE31w59H2/KK/a/zSDe2UB0VXXdpxL9Y8rMIihOZkpfc7rzdpo2HDv/Zwnp+Fq+MgseY1xKgTvnoOMv4Lhtd+xpO1zFoGtfvOM8XuRdA0U+rSroAi9KJD18OuNJj67A07gyltSDNHx48IUOtwmA9XzhdNl+CDoxy3k18L/XlDzjxhfVdN8ULm3rpeFqPsoyvzM2hPu1zzXhIS0ssfmfCQLi3hEPd3tfM3X2tRWkh+DSBbTC+7Hd7w1iQkdlOhPtrvC1Tt61ZpEMHfunXzWhTx5tt91QC0Zk5B2jK5Lq6FpixJebSXzlyqEGl2IwZMsZhJoqR4YlSCRZQLcmrxTqIJxf+F8ZloHyx2WlO0W+C5kt6V/vt1Ev/G4hiMAN3JFOszpmi4wata64+B54ATEZRdM+a+/FtxgDDks3TNlJi/ZArQyRUwHX0495OpOpTc+lWS3l2tN3gI3BqoLBy8yu/XAxajIZqV0DtTO6uPZF7QF91KX52V8tMX/vG2kG/AweAT1Dr8muOPyCCmbUyYFty7GRX8H8fALRZ9FuTm45sMwAPnRBarYEk6Gp+j1VqrTVriRAHgXlXfdcx3s7oTiRxTBhWQeBvugwG4qZobWtKfks7C7LEdP+DmzrqoVtW01M6vMmKhjgleWOlT+9QhqY8opz/ufE=
  template:
    metadata:
      name: demo-api-key
      namespace: soc-agent-demo
