apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockAutomountToken
metadata:
  name: block-automount-serviceaccount-token
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - soc-agent-demo
